CREATE DATABASE IF NOT EXISTS `oof` DEFAULT CHARACTER SET greek COLLATE greek_general_ci;
USE `oof`;

CREATE TABLE IF NOT EXISTS `oof` ( `name` VARCHAR(50) NOT NULL , `lastname` VARCHAR(50) NOT NULL , `USERNAME` TEXT NOT NULL , `PASSWORD` TEXT NOT NULL , `EMAIL` TEXT NOT NULL , `age` INT(5) NOT NULL , `birthday` DATE NOT NULL , `address` TEXT NOT NULL , `payment` TEXT NOT NULL , `comments` TEXT NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=greek;

